server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO