server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false


spring:
  application:
    name: service-registry
  profiles:
    active:
      - dev

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO