delete from ARTICLE;

insert into ARTICLE(summary,
                    country,
                    author,
                    link,
                    language,
                    media,
                    title,
                    mediaContent,
                    cleanUrl,
                    rights,
                    rank,
                    topic,
                    publishedDate,
                    id)
    values('summary',
           'country',
           'author',
           'link',
           'language',
           'media',
           'title',
           'mediaContent',
           'cleanUrl',
           'rights',
           'rank',
           'topic',
           'publishedDate',
           1);