server:
  port: 9090

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        thymeleaf: DEBUG

spring:
  application:
    name: tts-service
  profiles:
    active:
      - dev

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/